### ISSUE TITLE
Change "localhost" reference to 127.0.0.1

### ISSUE THREAD

**Issue by dmcmillan** [lab19digital/wp19#16]
@luke-siedle, would it affect people on other OS's to change the reference of "localhost" for DB_HOST to "127.0.0.1"? So line 47 of wp-config becomes `define('DB_HOST', '127.0.0.1');`

I found that I had to do this on my new Mac to get it to work, but not sure if this would break for other users or be ok.

**Comment by vtimbuc** [comment]
This can now be set while running the installation (gulp wp_init).
